import { Component, computed, input } from '@angular/core'

import {
	LucideArrowDown,
	LucideArrowLeft,
	LucideArrowRight,
	LucideArrowUp,
	LucideBan,
	LucideBuilding,
	LucideCalendar,
	LucideCalendarDays,
	LucideChartArea,
	LucideChartCandlestick,
	LucideCheck,
	LucideChevronDown,
	LucideChevronLeft,
	LucideChevronRight,
	LucideChevronUp,
	LucideCircleAlert,
	LucideCircleUserRound,
	LucideCloudDownload,
	LucideDynamicIcon,
	LucideEye,
	LucideEyeClosed,
	LucideFile,
	LucideHeart,
	LucideHouse,
	LucideKeyRound,
	LucideLandmark,
	LucideLink,
	LucideLoader,
	LucideLoaderCircle,
	LucideLockKeyhole,
	LucideMail,
	LucideMapPin,
	LucideMenu,
	LucideMoon,
	LucideSearch,
	LucideSend,
	LucideSettings,
	LucideShieldCheck,
	LucideShieldX,
	LucideShoppingBasket,
	LucideShoppingCart,
	LucideStar,
	LucideStarHalf,
	LucideSun,
	LucideThumbsDown,
	LucideThumbsUp,
	LucideTrash2,
	LucideTriangleAlert,
	LucideUser,
	LucideUserMinus,
	LucideUserPen,
	LucideUserPlus,
	LucideUsers,
	LucideX,
	LucideCircleCheck,
	LucideCloud,
	LucideCloudRain,
	LucideEllipsisVertical,
	LucideExternalLink,
	LucideInfo,
	LucidePlus,
	LucideZap,
} from '@lucide/angular'

import { IconType } from './icon.type'

@Component({
	imports: [LucideDynamicIcon],
	selector: 'lib-ui-icon',
	template: `<svg [size]="size()" [lucideIcon]="iconName()"></svg>`,
})
export class Icon {
	icon = input<IconType>('loader-circle')
	size = input<number>(24)

	iconName = computed(() => {
		const dic = {
			'loader-circle': LucideLoaderCircle,
			loader: LucideLoader,
			x: LucideX,
			check: LucideCheck,
			'key-round': LucideKeyRound,
			'lock-keyhole': LucideLockKeyhole,
			user: LucideUser,
			'user-minus': LucideUserMinus,
			'user-plus': LucideUserPlus,
			'user-pen': LucideUserPen,
			users: LucideUsers,
			'circle-user-round': LucideCircleUserRound,
			settings: LucideSettings,
			file: LucideFile,
			'cloud-download': LucideCloudDownload,
			'chevron-down': LucideChevronDown,
			'chevron-up': LucideChevronUp,
			'chevron-left': LucideChevronLeft,
			'chevron-right': LucideChevronRight,
			building: LucideBuilding,
			'shopping-cart': LucideShoppingCart,
			'shopping-basket': LucideShoppingBasket,
			heart: LucideHeart,
			'trash-2': LucideTrash2,
			star: LucideStar,
			'star-half': LucideStarHalf,
			'calendar-days': LucideCalendarDays,
			'eye-closed': LucideEyeClosed,
			eye: LucideEye,
			house: LucideHouse,
			landmark: LucideLandmark,
			'map-pin': LucideMapPin,
			sun: LucideSun,
			'thumbs-up': LucideThumbsUp,
			'thumbs-down': LucideThumbsDown,
			'triangle-alert': LucideTriangleAlert,
			ban: LucideBan,
			'shield-x': LucideShieldX,
			'shield-check': LucideShieldCheck,
			'chart-candlestick': LucideChartCandlestick,
			'chart-area': LucideChartArea,
			menu: LucideMenu,
			'circle-alert': LucideCircleAlert,
			search: LucideSearch,
			moon: LucideMoon,
			'arrow-right': LucideArrowRight,
			'arrow-left': LucideArrowLeft,
			'arrow-up': LucideArrowUp,
			'arrow-down': LucideArrowDown,
			send: LucideSend,
			mail: LucideMail,
			link: LucideLink,
			calendar: LucideCalendar,
			'circle-check': LucideCircleCheck,
			'ellipsis-vertical': LucideEllipsisVertical,
			'external-link': LucideExternalLink,
			plus: LucidePlus,
			zap: LucideZap,
			info: LucideInfo,
			cloud: LucideCloud,
			'cloud-rain': LucideCloudRain,
		}

		return dic[this.icon()]
	})
}
